version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=audit_app_admin.settings
    depends_on:
      - oracle

  oracle:
    image: oracleinanutshell/oracle-xe-11g
    environment:
      - ORACLE_ENABLE_XDB=true
      - ORACLE_PASSWORD=Oradoc_db1
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/u01/app/oracle/oradata

volumes:
  oracle-data:
